# Site settings
title: "博客标题"
author: "作者名"
description: "博客简介"
keywords: ""
biography: "个人简介"
colophon: "©版权标记"

baseurl: "/blog"
url: "https://une-saison.github.io"

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
